# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='album_art',
            field=models.FileField(upload_to=''),
        ),
    ]
